### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by jofftiquez** [jofftiquez/v-animate-css#3]

**Comment by jokari** [comment]
See #4

**Comment by liquidvisual** [comment]
What the

**Comment by fjeddy** [comment]
Just delete this repo and make it disappear from the face of the earth. If you can't maintain your own demo, and at the same time spend 9 months accepting someones PR that fixes your demo, then you are incapable of maintaining a repo.

**Comment by fjeddy** [comment]
Just delete this repo and make it disappear from the face of the earth. If you can't maintain your own demo, and at the same time spend 9 months accepting someones PR that fixes your demo, then you are incapable of maintaining a repo.
