### ISSUE TITLE
Documentation broken?

### ISSUE THREAD

**Issue by LeCoupa** [jofftiquez/v-animate-css#5]
Your documentation seems broken on my side. Animations are not triggered. I see this warning in my console.

```
Uncaught TypeError: Cannot read property 'scrollHeight' of null
```

Might be related?

**Comment by matiaslopezd** [comment]
@LeCoupa Yes totally, it's blocking all JS

**Comment by ankittaneja** [comment]
Same! Did you guys have any luck using the library?! Like should I even try to use!! @jofftiquez

**Comment by pmochine** [comment]
Same :D

**Comment by jofftiquez** [comment]
Hello, I apologize this hasn't been maintain very well. I will look into this issue. Thank you! Stay safe.
